//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prog1
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentMark
    {
        public int id { get; set; }
        public Nullable<int> studentid { get; set; }
        public Nullable<int> examid { get; set; }
        public Nullable<int> mark { get; set; }
    }
}
