//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prog1
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject
    {
        public int id { get; set; }
        public Nullable<long> Departmentid { get; set; }
        public string Name { get; set; }
        public Nullable<int> MinimumDegree { get; set; }
        public Nullable<short> Term { get; set; }
        public Nullable<short> Year { get; set; }
    }
}
